version: '3'
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/conf/nginx.conf:/etc/nginx/nginx.conf
  user-service:
    image: user-service
    ports:
      - "8080:9090"
  order-service:
    image: order-service
    ports:
      - "8081:9090"
  cart-service:
    image: cart-service
    ports:
      - "8082:9090"
  catalog-service:
    image: catalog-service
    ports:
      - "8083:9090"
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper