version: '3'
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/conf/nginx.conf:/etc/nginx/nginx.conf
  user-service:
    image: fd-user-service
    ports:
      - "8081:8080"
  # order-service:
  #   image: fd-order-service
  #   ports:
  #     - "8082:8080"
  # cart-service:
  #   image: fd-cart-service
  #   ports:
  #     - "8083:8080"
  # catalog-service:
  #   image: fd-catalog-service
  #   ports:
  #     - "8084:8080"
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper