spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery
    username: root
    password: Mylovely
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8082

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data